option(DOCUMENT_VIEWER_ENABLE_LTO "Enable link-time optimization in optimized builds" ON)
if(DOCUMENT_VIEWER_ENABLE_LTO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT lto_supported OUTPUT lto_error LANGUAGES CXX)
    if(NOT lto_supported)
        message(FATAL_ERROR "LTO is not supported by this toolchain: ${lto_error}\nDisable with -DDOCUMENT_VIEWER_ENABLE_LTO=OFF.")
    endif()
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO ON)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL ON)
    message(STATUS "LTO enabled for Release, RelWithDebInfo, and MinSizeRel")
endif()
